server {
    listen 80;

    server_name s-bins.duckdns.org www.s-bins.duckdns.org;

    #SSL (Certbot)
    location /.well-known/acme-challenge/ {
        alias /var/www/html/.well-known/acme-challenge/;
        try_files $uri =404;
    }

    # Serve React build
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Proxy API requests to backend container
    location /api/ {
        proxy_pass http://sbin-server:3002/;  # backend container name & port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
